function ra_start

%define parameters for figure position
figwidth = 400;
figheight = 200;

%define space between rows and first row location
rowspace = 25;
row = figheight - rowspace*2;

ra_gui= figure('unit','pix','Visible','off',...
  'position',[400 400 figwidth figheight],...
  'menub','no',...
  'numbertitle','off',...
  'resize','off');
movegui(ra_gui,'center');

%Print the name of the loaded dataset
uicontrol(ra_gui,'Style','text','fontsize',16,...
    'HorizontalAlignment','center',...
    'String','What would you like to do?',...
    'Position',[0 row figwidth 25]);          

%Create a back button that will take the user back to ra_start
uicontrol(ra_gui,'Style','push','fontsize',14,...
    'HorizontalAlignment','center',...
    'String','<html><center>Process <br>New Data',...
    'Position', [figwidth/8 25 figwidth/3 75],...
    'Callback',@ra_startproc); 

%Create button that will check the inputs and begin processing the data
uicontrol(ra_gui,'Style','push','fontsize',14,...
    'HorizontalAlignment','center',...
    'String','View Results',...
    'Position', [5*figwidth/8 25 figwidth/3 75],...
    'Callback',{@ra_startview}); 

set(ra_gui,'Visible','on');

end
