data = ra_loadfile('file',...
    '/Users/Peter/Dropbox/Documents/Publications-In Progress/ERP_ReliabilityRev/NewScripts/ADRel_AllERPdata_Test.xlsx',...
    'meascol','Measurement','groupcol','group','eventcol','event');

ra_computerel('data',data);